apiVersion: v1
kind: Service
metadata:
    name: clusteip-service
spec:
    selector:
        app: webserver
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    type: ClusterIP
