apiVersion: v1
kind: Service
metadata:
    name: clusterip-service
spec:
    selector:
        app: webserver
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    ports:
        - protocol: TCP
          port: 5672
          targetPort: 5672
    type: ClusterIP
