apiVersion: v1
type: Pod
metadata:
    name: multicontainerpod
spec:
    containers:
        - name: firstcontainer
          image: nginx:latest
        - name: secondcontainer
          image: httpd:latest
