apiVersion: v1
kind: Pod
metadata:
    name: nginx-affinity-node
spec:
    affinity:
        nodeAffinity:
            requireDuringSchedulingIgnoreDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                        - key: zone
                          operator: In
                          values:
                              - us-central-1
                              - eu-west-1
            preferredDuringSchedulingIgnoreDuringExecution:
                - weight: 1
                  preference:
                      matchExpressions:
                          - key: zonedrbackup
                            operator: In
                            values:
                                - europe
    containers:
        - name: nginx
          image: nginx:latest
