apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    labels:
        run: pod2
        color: red
    name:
        restrictpod
spec:
    containers:
        - image: nginx
          name: restriccontainer
          resources:
              requests:
                  memory: 100Mi
    dnsPolicy: ClusterFirst
    restartPolicy: OnFailure
status: {}
