apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    labels:
        run: pod1
        color: blue
    name: singlepod
spec:
    containers:
        - name: nginx
          image: nginx
          resources: {}
    dnsPolicy: ClusterFirst
    restartPolicy: OnFailure
status: {}
